/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jschool.gui;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jschool.infraestrutura.Ambiente;
import jschool.infraestrutura.ConexaoFactory;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author andre
 */
public class JFrameJSchool extends javax.swing.JFrame {

    /**
     * Creates new form JFrameJSchool
     */
    public JFrameJSchool() {
        initComponents();
        carregarLabelInfo();
    }
    
    private void carregarLabelInfo(){
        jlbUsuario.setText(Ambiente.getUsuarioLogado().getNome());
        jlbBancoDados.setText(Ambiente.nomeBancoDados());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jdpJschool = new javax.swing.JDesktopPane();
        jpRodape = new javax.swing.JPanel();
        jlbBancoDados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmbJschool = new javax.swing.JMenuBar();
        jmPessoas = new javax.swing.JMenu();
        jmiAlunos = new javax.swing.JMenuItem();
        jmiProfessores = new javax.swing.JMenuItem();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmiCursos = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmiMatriculas = new javax.swing.JMenuItem();
        jmTurmas = new javax.swing.JMenu();
        jmiTurmas = new javax.swing.JMenuItem();
        jmiFrequencias = new javax.swing.JMenuItem();
        jmiNotas = new javax.swing.JMenuItem();
        jmInstitucional = new javax.swing.JMenu();
        jmiInsituicaoEnsino = new javax.swing.JMenuItem();
        jmRelPessoas = new javax.swing.JMenu();
        jmRelEducacional = new javax.swing.JMenu();
        jmiListagemPessoas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiListagemCursos = new javax.swing.JMenuItem();
        jmiListagemTurmas = new javax.swing.JMenuItem();
        jmiTurmasCurso = new javax.swing.JMenuItem();
        jmiListagemTurmasPeriodo = new javax.swing.JMenuItem();
        jmiListagemTurmasCursoQtd = new javax.swing.JMenuItem();
        jmFerramentas = new javax.swing.JMenu();
        jmiTemas = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JSchool");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(new java.awt.Dimension(762, 10));
        setState(JFrame.MAXIMIZED_BOTH);

        jdpJschool.setBackground(new java.awt.Color(204, 204, 204));

        jpRodape.setEnabled(false);
        jpRodape.setMaximumSize(new java.awt.Dimension(762, 14));
        jpRodape.setMinimumSize(new java.awt.Dimension(762, 14));
        jpRodape.setPreferredSize(new java.awt.Dimension(762, 14));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuário conectado:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Banco de dados:");

        javax.swing.GroupLayout jpRodapeLayout = new javax.swing.GroupLayout(jpRodape);
        jpRodape.setLayout(jpRodapeLayout);
        jpRodapeLayout.setHorizontalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbBancoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jpRodapeLayout.setVerticalGroup(
            jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRodapeLayout.createSequentialGroup()
                .addGroup(jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbBancoDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jmPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/reading.png"))); // NOI18N
        jmPessoas.setText("Pessoas");

        jmiAlunos.setText("Alunos");
        jmiAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunosActionPerformed(evt);
            }
        });
        jmPessoas.add(jmiAlunos);

        jmiProfessores.setText("Professores");
        jmiProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProfessoresActionPerformed(evt);
            }
        });
        jmPessoas.add(jmiProfessores);

        jmiUsuarios.setText("Usuários");
        jmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuariosActionPerformed(evt);
            }
        });
        jmPessoas.add(jmiUsuarios);

        jmbJschool.add(jmPessoas);

        jmiCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/scholarship.png"))); // NOI18N
        jmiCursos.setText("Educacional");

        jMenuItem5.setText("Cursos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmiCursos.add(jMenuItem5);

        jmiMatriculas.setText("Matrículas");
        jmiMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMatriculasActionPerformed(evt);
            }
        });
        jmiCursos.add(jmiMatriculas);

        jmTurmas.setText("Turmas");

        jmiTurmas.setText("Turmas");
        jmiTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTurmasActionPerformed(evt);
            }
        });
        jmTurmas.add(jmiTurmas);

        jmiFrequencias.setText("Frequências");
        jmiFrequencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrequenciasActionPerformed(evt);
            }
        });
        jmTurmas.add(jmiFrequencias);

        jmiNotas.setText("Notas");
        jmiNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNotasActionPerformed(evt);
            }
        });
        jmTurmas.add(jmiNotas);

        jmiCursos.add(jmTurmas);

        jmbJschool.add(jmiCursos);

        jmInstitucional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/school.png"))); // NOI18N
        jmInstitucional.setText("Insititucional");

        jmiInsituicaoEnsino.setText("Instituição de ensino");
        jmiInsituicaoEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInsituicaoEnsinoActionPerformed(evt);
            }
        });
        jmInstitucional.add(jmiInsituicaoEnsino);

        jmbJschool.add(jmInstitucional);

        jmRelPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/relatorio24.png"))); // NOI18N
        jmRelPessoas.setText("Relatórios");

        jmRelEducacional.setText("Pessoas");

        jmiListagemPessoas.setText("Listagem de pessoas");
        jmiListagemPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListagemPessoasActionPerformed(evt);
            }
        });
        jmRelEducacional.add(jmiListagemPessoas);

        jmRelPessoas.add(jmRelEducacional);

        jMenu3.setText("Educacional");

        jmiListagemCursos.setText("Listagem de cursos");
        jmiListagemCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListagemCursosActionPerformed(evt);
            }
        });
        jMenu3.add(jmiListagemCursos);

        jmiListagemTurmas.setText("Listagem de turmas");
        jMenu3.add(jmiListagemTurmas);

        jmiTurmasCurso.setText("Listagem de turmas por curso");
        jmiTurmasCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTurmasCursoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiTurmasCurso);

        jmiListagemTurmasPeriodo.setText("Listagem de turmas por período");
        jmiListagemTurmasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListagemTurmasPeriodoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiListagemTurmasPeriodo);

        jmiListagemTurmasCursoQtd.setText("Quantidade turmas por curso");
        jmiListagemTurmasCursoQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListagemTurmasCursoQtdActionPerformed(evt);
            }
        });
        jMenu3.add(jmiListagemTurmasCursoQtd);

        jmRelPessoas.add(jMenu3);

        jmbJschool.add(jmRelPessoas);

        jmFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/wrench.png"))); // NOI18N
        jmFerramentas.setText("Ferramentas");

        jmiTemas.setText("Temas");
        jmiTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTemasActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiTemas);

        jmbJschool.add(jmFerramentas);

        jmSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jschool/icons/info.png"))); // NOI18N
        jmSobre.setText("Sobre");

        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmSobre.add(jmiSobre);

        jmbJschool.add(jmSobre);

        setJMenuBar(jmbJschool);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpJschool)
            .addComponent(jpRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpJschool, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiInsituicaoEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInsituicaoEnsinoActionPerformed
        JIFrameInstituicaoEnsino frameInstituicao = new JIFrameInstituicaoEnsino();
        jdpJschool.add(frameInstituicao);
        frameInstituicao.setVisible(true);
    }//GEN-LAST:event_jmiInsituicaoEnsinoActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JIFrameSobre frameSobre = new JIFrameSobre();
        jdpJschool.add(frameSobre);
        frameSobre.setVisible(true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunosActionPerformed
        JIFrameAlunos frameAlunos = new JIFrameAlunos();
        jdpJschool.add(frameAlunos);
        frameAlunos.setVisible(true);
    }//GEN-LAST:event_jmiAlunosActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JIFrameCursos frameCursos = new JIFrameCursos();
        jdpJschool.add(frameCursos);
        frameCursos.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmiTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTemasActionPerformed
        JIFrameTemas frameTemas = new JIFrameTemas();
        jdpJschool.add(frameTemas);
        frameTemas.setVisible(true);
    }//GEN-LAST:event_jmiTemasActionPerformed

    private void jmiProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProfessoresActionPerformed
        JIFrameProfessores frameProfessores = new JIFrameProfessores();
        jdpJschool.add(frameProfessores);
        frameProfessores.setVisible(true);
    }//GEN-LAST:event_jmiProfessoresActionPerformed

    private void jmiTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTurmasActionPerformed
        JIFrameTurmas frameTurmas = new JIFrameTurmas();
        jdpJschool.add(frameTurmas);
        frameTurmas.setVisible(true);
    }//GEN-LAST:event_jmiTurmasActionPerformed

    private void jmiListagemPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListagemPessoasActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/jschool/relatorios/rel_pessoas.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoFactory.getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório");
        }
    }//GEN-LAST:event_jmiListagemPessoasActionPerformed

    private void jmiListagemCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListagemCursosActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/jschool/relatorios/rel_cursos.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoFactory.getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório");
        }
    }//GEN-LAST:event_jmiListagemCursosActionPerformed

    private void jmiListagemTurmasCursoQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListagemTurmasCursoQtdActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/jschool/relatorios/rel_top_cursos.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatoio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoFactory.getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório");
        }
    }//GEN-LAST:event_jmiListagemTurmasCursoQtdActionPerformed

    private void jmiTurmasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTurmasCursoActionPerformed
        
        JDRelatorioTurmasCurso dialogRelatorio = new JDRelatorioTurmasCurso(this, true);
        dialogRelatorio.setVisible(true);

    }//GEN-LAST:event_jmiTurmasCursoActionPerformed

    private void jmiListagemTurmasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListagemTurmasPeriodoActionPerformed
        
        JDRelatorioTurmaPeriodo dialogRelatorio = new JDRelatorioTurmaPeriodo(this, true);
        dialogRelatorio.setVisible(true);
        
    }//GEN-LAST:event_jmiListagemTurmasPeriodoActionPerformed

    private void jmiMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMatriculasActionPerformed
        JIFrameMatriculas frameMatriculas = new JIFrameMatriculas();
        frameMatriculas.setVisible(true);
        jdpJschool.add(frameMatriculas);
    }//GEN-LAST:event_jmiMatriculasActionPerformed

    private void jmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuariosActionPerformed
        JIFrameUsuarios frameUsuarios = new JIFrameUsuarios();
        jdpJschool.add(frameUsuarios);
        frameUsuarios.setVisible(true);
    }//GEN-LAST:event_jmiUsuariosActionPerformed

    private void jmiFrequenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrequenciasActionPerformed
        JIFrameFrequencias frameFrequencias = new JIFrameFrequencias();
        jdpJschool.add(frameFrequencias);
        frameFrequencias.setVisible(true);
    }//GEN-LAST:event_jmiFrequenciasActionPerformed

    private void jmiNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNotasActionPerformed
        JIFrameNotas frameNotas = new JIFrameNotas();
        jdpJschool.add(frameNotas);
        frameNotas.setVisible(true);
    }//GEN-LAST:event_jmiNotasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdpJschool;
    private javax.swing.JLabel jlbBancoDados;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JMenu jmFerramentas;
    private javax.swing.JMenu jmInstitucional;
    private javax.swing.JMenu jmPessoas;
    private javax.swing.JMenu jmRelEducacional;
    private javax.swing.JMenu jmRelPessoas;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenu jmTurmas;
    private javax.swing.JMenuBar jmbJschool;
    private javax.swing.JMenuItem jmiAlunos;
    private javax.swing.JMenu jmiCursos;
    private javax.swing.JMenuItem jmiFrequencias;
    private javax.swing.JMenuItem jmiInsituicaoEnsino;
    private javax.swing.JMenuItem jmiListagemCursos;
    private javax.swing.JMenuItem jmiListagemPessoas;
    private javax.swing.JMenuItem jmiListagemTurmas;
    private javax.swing.JMenuItem jmiListagemTurmasCursoQtd;
    private javax.swing.JMenuItem jmiListagemTurmasPeriodo;
    private javax.swing.JMenuItem jmiMatriculas;
    private javax.swing.JMenuItem jmiNotas;
    private javax.swing.JMenuItem jmiProfessores;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiTemas;
    private javax.swing.JMenuItem jmiTurmas;
    private javax.swing.JMenuItem jmiTurmasCurso;
    private javax.swing.JMenuItem jmiUsuarios;
    private javax.swing.JPanel jpRodape;
    // End of variables declaration//GEN-END:variables
}
