/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jschool.gui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import jschool.infraestrutura.GerenciadorGUI;
import jschool.infraestrutura.Mensagem;
import jschool.infraestrutura.Tema;

/**
 *
 * @author andre
 */
public class JIFrameTemas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrameTemas
     */
    public JIFrameTemas() {
        initComponents();
        carregarTemas();
    }

    private void carregarTemas() {
        try {
            DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
            UIManager.LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
            Tema temaSelecionado = null;

            for (UIManager.LookAndFeelInfo laf : lafs) {
                
                Tema tema = new Tema(laf.getName(), laf.getClassName());
                comboBoxModel.addElement(tema);
                
                if(tema.getNomeClass().equals(GerenciadorGUI.getLookAndFeelClass())){
                    temaSelecionado = tema;
                }
            }
            jcbTemas.setModel(comboBoxModel);
            
            if(temaSelecionado != null){
                jcbTemas.getModel().setSelectedItem(temaSelecionado);
            }
        } catch (Exception ex) {
            
            Mensagem.erro("Problema ao carregar temas: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbTemas = new javax.swing.JComboBox<>();
        jbtConfirmar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Configuração de tema");

        jLabel1.setText("Tema");

        jbtConfirmar.setText("Confirmar");
        jbtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTemas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jbtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtCancelar, jbtConfirmar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirmar)
                    .addComponent(jbtCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmarActionPerformed
        try {
            Tema tema = (Tema) jcbTemas.getSelectedItem();
            GerenciadorGUI.setLookAndFeel(tema.getNomeClass());

            Mensagem.aviso("Reinicie o programa para aplicar as alterações");
            this.dispose();
        } catch (Exception e) {
            Mensagem.erro("Problema ao alterar tema: " + e.getMessage());
        }
    }//GEN-LAST:event_jbtConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtConfirmar;
    private javax.swing.JComboBox<String> jcbTemas;
    // End of variables declaration//GEN-END:variables
}
